<?php

namespace ContainerMzZQBr8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReisgegevensTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ReisgegevensType' shared autowired service.
     *
     * @return \App\Form\ReisgegevensType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ReisgegevensType.php';

        return $container->privates['App\\Form\\ReisgegevensType'] = new \App\Form\ReisgegevensType();
    }
}
