<?php

namespace ContainerMzZQBr8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeergaveZoekerTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\WeergaveZoekerType' shared autowired service.
     *
     * @return \App\Form\WeergaveZoekerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/WeergaveZoekerType.php';

        return $container->privates['App\\Form\\WeergaveZoekerType'] = new \App\Form\WeergaveZoekerType();
    }
}
