<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDWjc3mP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDWjc3mP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDWjc3mP.legacy');


    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDWjc3mP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVHJgJOH\App_KernelDevDebugContainer([
    'container.build_hash' => 'VHJgJOH',
    'container.build_id' => '08bc2f40',
    'container.build_time' => 1648543382,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVHJgJOH');

