<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA9srOqV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA9srOqV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA9srOqV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA9srOqV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA9srOqV\App_KernelDevDebugContainer([
    'container.build_hash' => 'A9srOqV',
    'container.build_id' => 'd7f716b2',
    'container.build_time' => 1648562349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA9srOqV');
