<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWXrjDbZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWXrjDbZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWXrjDbZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWXrjDbZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWXrjDbZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'WXrjDbZ',
    'container.build_id' => '8a3efbd7',
    'container.build_time' => 1648119120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWXrjDbZ');
